# Copyright 2019 The Kepler Developers
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

dist: trusty
sudo: required

language: rust

rust:
  - stable

git:
  depth: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - cmake
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev

cache:
  cargo: true
  timeout: 240
  directories:
    - $HOME/.cargo
    - $TRAVIS_BUILD_DIR/target

env:
  global:
    - RUST_BACKTRACE="1"
    - RUST_FLAGS="-C debug-assertions"

matrix:
  include:
    - os: linux
      env: CI_JOB="test"        CI_JOB_ARGS="servers"
    - os: linux
      env: CI_JOB="test"        CI_JOB_ARGS="chain core"
    - os: linux
      env: CI_JOB="test"        CI_JOB_ARGS="pool p2p src"
    - os: linux
      env: CI_JOB="test"        CI_JOB_ARGS="keychain wallet"
    - os: linux
      env: CI_JOB="test"        CI_JOB_ARGS="api util store"
    - os: linux
      env: CI_JOB="release"     CI_JOB_ARGS=
    - os: osx
      env: CI_JOB="release"     CI_JOB_ARGS=
#    - os: windows
#      env: CI_JOB="release"     CI_JOB_ARGS=

script: .ci/general-jobs

before_cache:
  - rm -rf $TRAVIS_BUILD_DIR/target/tmp

before_deploy:
  - bash .ci/release-jobs

deploy:
  provider: releases
  api_key:
    secure: MRhdzzB0SQ0XTyjW7Kzp/OeHKIzMsVDUm2Is2SHSvDHrxU+Ix4RWOQPuBPNBdC/lHVZIfQFVVUSJbpX0ofZxvBTyHsRCxDWJSBuzWrmX2nVvvB+aReCCNXqasWdc/qQSH7w+WRG90CKvefQfv7jhFeF+WL2ckKWlWeQzIoW3boujmCZR8cLzJWD7D5MQD7UP3Fdh0Gl2OhMl05s39bBGNM/NZTDugIpGY8f1hTQ5W2kdFkPkqz5rnUIwa17CfR0j7MO0bQHmekfAOx9wPtKSlnrG8bN2uarGFpOvPLiNQtdIflasaTdu4BeH9EHiBPJHFjaUnkaQmmU4uqYq5cqLQg3h4ijhoxW2jL/qELi3XfzsBihfw9lc/kKS1cxiqRiHyH+oJZi/i8wg8a/82V93WXFTT7qbI4YurLRUDaoaWf2CxymK2VtqaTS4iQ0SW/BKpqvQWR9LwI8vRd67zVt4RUBvCOF/3FKhC3sEdxkN0ld5C23Uko9QgLps13BE+7aywvUSRt21aDASt9MHpAZlViMjipie2LbrSgrElziFiWN4huCBBkI1iAAm1EhjyQwV+gOhbuhJSq20lUlqGKJewE/EhqoybtasxzfIhMRi9X5vITmkD8SAMHmNk5z97kws0ddiTmtTuppV9t+hGKNh8nZcbmBlneWG/d2nUejTshg=
  file_glob: true
  file: target/release/kepler-*.tgz*
  skip_cleanup: true
  on:
    repo: keplernetwork/kepler
    tags: true
